# fly.toml app configuration file generated for biztrip on 2025-03-31T07:58:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'biztrip'
primary_region = 'sjc'

[http_service]
  internal_port = 8086
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="agents_storage"
  destination="/app/runtime"
  processes = ["app"]
  